[package]
name = "rustkernel"
version = "0.0.2"
authors = ["Jack Clayton"]
description = "Kernel for running Rust code interactively in VS Code, will later be extended to other platforms"
license = "MIT"
readme = "README.md"
repository = "https://github.com/rustnote/rustkernel"
documentation = "https://rustnote.com"
homepage = "https://rustnote.com"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[net]
git-getch-with-cli = true
